# Generated by Django 3.0.5 on 2021-01-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Created', models.DateTimeField()),
                ('Directory', models.CharField(default='', max_length=255)),
                ('epoch', models.CharField(default='', max_length=255)),
                ('batch', models.CharField(default='', max_length=255)),
                ('learningrate', models.CharField(default='', max_length=255)),
                ('User', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MachineClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Machine_ID', models.CharField(default='0', max_length=255)),
                ('ClassEncoding', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
