# Generated by Django 3.0.5 on 2021-01-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachapp', '0003_machineclass_classencoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='User',
            field=models.CharField(default='', max_length=255),
        ),
    ]
