# Generated by Django 3.0.5 on 2021-01-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='batch',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='machine',
            name='epoch',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='machine',
            name='learningrate',
            field=models.CharField(default='', max_length=255),
        ),
    ]
