# Generated by Django 3.0.5 on 2021-01-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachapp', '0002_auto_20210106_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineclass',
            name='ClassEncoding',
            field=models.CharField(default='', max_length=255),
        ),
    ]
